### CREATE ARBITRE
POST http://localhost:3000/arbitres
Content-Type: application/json

{
  "nom": "Hakimi",
  "prenom": "Karim",
  "nationalite": "Maroc",
  "confederation": "CAF",
  "categorie": "Referee",
  "experience": 10,
  "statut": "actif"
}

### GET ARBITRES
GET http://localhost:3000/arbitres

### CREATE MATCH
POST http://localhost:3000/matchs
Content-Type: application/json

{
  "equipeDomicile": "Maroc",
  "equipeExterieur": "France",
  "stade": "Hassan II",
  "villeHote": "Casablanca",
  "dateMatch": "2026-07-10",
  "phase": "Groupes"
}

### CREATE AFFECTATION
POST http://localhost:3000/affectations
Content-Type: application/json

{
  "arbitreId": 1,
  "matchId": 1,
  "role": "central"
}